# Generated by Django 2.1.5 on 2019-02-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('zshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zshop.Product'),
        ),
    ]
