# Generated by Django 2.1.5 on 2019-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190204_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_details',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_details',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
